const events = [
    {
      onClick: () => window.open('https://example.com'),
      status: 'Live',
      statusHref: '#',
      prize: '$1000',
      prizeHref: '#',
      logoSrc: '/logo1.png',
      title: 'Hackathon for Beginners',
      titleHref: '#',
      targetAudience: 'Beginners',
      organization: 'TechGuru',
      mode: 'Online',
      tagList: ['Hackathon', 'Beginner'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Expired',
      statusHref: '#',
      prize: '$2000',
      prizeHref: '#',
      logoSrc: '/logo2.png',
      title: 'Advanced Coding Challenge',
      titleHref: '#',
      targetAudience: 'Advanced Developers',
      organization: 'CodeMaster',
      mode: 'Offline',
      tagList: ['Coding Challenge', 'Advanced'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Live',
      statusHref: '#',
      prize: '$1500',
      prizeHref: '#',
      logoSrc: '/logo3.png',
      title: 'AI Hackathon',
      titleHref: '#',
      targetAudience: 'AI Enthusiasts',
      organization: 'AI Innovators',
      mode: 'Online',
      tagList: ['Hackathon', 'AI'],
    },
    // Add more dummy data entries below
    {
      onClick: () => window.open('https://example.com'),
      status: 'Live',
      statusHref: '#',
      prize: '$800',
      prizeHref: '#',
      logoSrc: '/logo4.png',
      title: 'Web Development Bootcamp',
      titleHref: '#',
      targetAudience: 'Web Developers',
      organization: 'DevCamp',
      mode: 'Online',
      tagList: ['Bootcamp', 'Web Development'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Upcoming',
      statusHref: '#',
      prize: '$500',
      prizeHref: '#',
      logoSrc: '/logo5.png',
      title: 'Mobile App Design Workshop',
      titleHref: '#',
      targetAudience: 'Designers',
      organization: 'DesignHub',
      mode: 'Offline',
      tagList: ['Workshop', 'Design', 'Mobile'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Live',
      statusHref: '#',
      prize: '$1200',
      prizeHref: '#',
      logoSrc: '/logo6.png',
      title: 'Blockchain Conference',
      titleHref: '#',
      targetAudience: 'Blockchain Enthusiasts',
      organization: 'Blockchain Summit',
      mode: 'Online',
      tagList: ['Conference', 'Blockchain'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Expired',
      statusHref: '#',
      prize: '$3000',
      prizeHref: '#',
      logoSrc: '/logo7.png',
      title: 'Data Science Hackathon',
      titleHref: '#',
      targetAudience: 'Data Scientists',
      organization: 'DataWorks',
      mode: 'Offline',
      tagList: ['Hackathon', 'Data Science'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Live',
      statusHref: '#',
      prize: '$1500',
      prizeHref: '#',
      logoSrc: '/logo8.png',
      title: 'Machine Learning Workshop',
      titleHref: '#',
      targetAudience: 'Machine Learning Enthusiasts',
      organization: 'ML Academy',
      mode: 'Online',
      tagList: ['Workshop', 'Machine Learning'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Upcoming',
      statusHref: '#',
      prize: '$700',
      prizeHref: '#',
      logoSrc: '/logo9.png',
      title: 'Cybersecurity Seminar',
      titleHref: '#',
      targetAudience: 'Security Professionals',
      organization: 'SecureTech',
      mode: 'Offline',
      tagList: ['Seminar', 'Cybersecurity'],
    },
    {
      onClick: () => window.open('https://example.com'),
      status: 'Live',
      statusHref: '#',
      prize: '$2000',
      prizeHref: '#',
      logoSrc: '/logo10.png',
      title: 'UX/UI Design Challenge',
      titleHref: '#',
      targetAudience: 'Designers',
      organization: 'DesignMaster',
      mode: 'Online',
      tagList: ['Design Challenge', 'UX/UI'],
    },
    // Add more dummy data entries as needed
  ];
  
  export default events;
  